/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

/**
 *
 * @author elias
 */
public class InfoPanel extends javax.swing.JPanel {
    private javax.swing.JPanel panelElementos = new javax.swing.JPanel();
    private JScrollPane panelDatos  = new JScrollPane(panelElementos);
    

    /**
     * Creates new form InfoPanel
     */
    public InfoPanel() {
        initComponents();
    }
    
    public JScrollPane getPanelDatos(){
        panelElementos.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        
        panelDatos.setBackground(Color.WHITE);
        panelElementos.setBackground(Color.WHITE);

        panelDatos.setBorder(null);

        return panelDatos;
    }
    
    
    public void agregaProductoOrMatPrima(String nombre, int cantidadInt){
        String producto=nombre;
        String cantidad = "Cantidad: "+Integer.toString(cantidadInt);
        
        JLabel labelProducto = new JLabel();
        JLabel labelCantidad = new JLabel();
        JLabel espacio = new JLabel();
        
        labelProducto.setText(producto);
        labelCantidad.setText(cantidad);
        espacio.setText("--------------------");

        panelElementos.add(espacio);
        panelElementos.add(labelProducto);
        panelElementos.add(labelCantidad);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
