/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import logica.Cliente;
import logica.Producto;
import logica.ControladorInterfaces;
import logica.Pedido;

/**
 *
 * @author elias
 */
public class VistaHistorialCliente extends javax.swing.JFrame {
    private static DefaultTableModel modeloTabla;
    private DefaultListModel model;
    private Cliente cliente;
    /**
     * Creates new form VistaDetallePedido
     */
    public VistaHistorialCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        modeloTabla = (DefaultTableModel) tablaPedido.getModel(); 
        this.model = new DefaultListModel();
        listaProductos.setModel(this.model);
        tablaPedido.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                int fila = tablaPedido.getSelectedRow();
                if (fila > -1) {
                    model.clear();
                    for(Producto p: cliente.getHistorialPedidos().get(fila).getProductos().keySet()){
                        model.addElement("Producto: " + p.getNombre());
                        model.addElement("Cantidad: " + cliente.getHistorialPedidos().get(fila).getProductos().get(p));
                        model.addElement("_______________________");
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloNombre = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JLabel();
        resumenProductos = new javax.swing.JLabel();
        panelSuperior = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedido = new javax.swing.JTable();
        btnOK = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloNombre.setText("Nombre Cliente:");
        getContentPane().add(tituloNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        getContentPane().add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        resumenProductos.setText("Productos: ");
        getContentPane().add(resumenProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, 20));

        panelSuperior.setBackground(new java.awt.Color(153, 197, 175));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo64x64.png"))); // NOI18N

        titulo.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("DETALLE PEDIDO");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(icon)
                .addGap(18, 18, 18)
                .addComponent(titulo)
                .addContainerGap(324, Short.MAX_VALUE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(icon)
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(18, 18, 18))
        );

        getContentPane().add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 70));

        listaProductos.setBackground(new java.awt.Color(242, 242, 242));
        listaProductos.setModel(new javax.swing.AbstractListModel<String>() {

            String[] strings = {"item 1"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }

        });
        listaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listaProductos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 190, 210));

        tablaPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Solicitud", "Precio Cancelado", "Fecha Retiro", "Estado"
            }
        ));
        tablaPedido.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tablaPedidoPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPedido);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 400, 210));

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 110, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoLargo.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 650, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        ControladorInterfaces.habilitarClientes(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    private void tablaPedidoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tablaPedidoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaPedidoPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaHistorialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaHistorialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaHistorialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaHistorialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaHistorialCliente().setVisible(true);
            }
        });
    }
    
    public void inicializaTabla(Cliente cliente){
        this.cliente = cliente;
        modeloTabla.setRowCount(0);
        model.clear();
        model.addElement("<html>Seleccione un pedido <br> para ver detalles.</html>");
        nombreCliente.setText(this.cliente.getNombreCliente());
        ArrayList<Pedido> pedidos = this.cliente.getHistorialPedidos();
        String pattern = "dd/MM/yyyy";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        for(Pedido p: pedidos){
            anadirFila(simpleDateFormat.format(p.getFechaSolicitud()), p.getPrecioAbonado(),
                    simpleDateFormat.format(p.getFechaRetiro()), p.getEstado());
        }
        
        
    }
    
    private void anadirFila(String fechaSolicitud, int precioCancelado, String fechaRetiro,
            String estado) {
        Object[] row = {fechaSolicitud, precioCancelado, fechaRetiro, estado};
        modeloTabla.addRow(row);
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel icon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JLabel nombreCliente;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JLabel resumenProductos;
    private javax.swing.JTable tablaPedido;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloNombre;
    // End of variables declaration//GEN-END:variables
}
