/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import logica.Almacen;
import logica.ControladorInterfaces;
import logica.Pedido;
import logica.Producto;


/**
 *
 * @author elias
 */
public class VistaNuevoPedido extends javax.swing.JFrame {
    private DefaultListModel model;
    private HashMap<Producto, Integer> productos;
    private int total;
    private Almacen almacen;
    private int contador;

    /**
     * Creates new form PaginaPrincipalFX
     */
    public VistaNuevoPedido() {
        initComponents();
        this.setLocationRelativeTo(null);
        productos = new HashMap<>();
        
        total = 0;
        contador = 0;
        this.model = new DefaultListModel();
        listaProductos.setModel(this.model);
        String pattern = "dd-MM-yyyy";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        Date hoy = new Date();
        fSolicitud.setText(simpleDateFormat.format(hoy));
    }
    
    public Almacen getAlmacen() {
        return almacen;
    }

    public void setAlmacen(Almacen almacen) {
        boxProductos.removeAllItems();
        this.almacen = almacen;
        for(Producto p: this.almacen.getProductos()){
            boxProductos.addItem(p.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtProducto = new javax.swing.JLabel();
        txtFechaSolicitud = new javax.swing.JLabel();
        txtPrecioTotal = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JLabel();
        txtCliente = new javax.swing.JLabel();
        txtNCliente = new javax.swing.JLabel();
        txtNumero = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JLabel();
        txtFechaRetiro = new javax.swing.JLabel();
        txtPrecioAbonado = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        fSolicitud = new javax.swing.JTextField();
        precioAbonado = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        descuento = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        fRetiro = new javax.swing.JTextField();
        boxProductos = new javax.swing.JComboBox<>();
        correo = new javax.swing.JTextField();
        boxCliente = new javax.swing.JComboBox<>();
        bVolver = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        precioTotal = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        txt$ = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JLabel();
        btnAplicarDscto = new javax.swing.JButton();
        resumenPedido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        panelSuperior = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProducto.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtProducto.setText("Producto:");
        getContentPane().add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        txtFechaSolicitud.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtFechaSolicitud.setText("Fecha Solicitud:");
        getContentPane().add(txtFechaSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        txtPrecioTotal.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtPrecioTotal.setText("Precio Total:");
        getContentPane().add(txtPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        txtDescuento.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtDescuento.setText("Descuento:");
        getContentPane().add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 80, 20));

        txtCliente.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtCliente.setText("Clientes:");
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));

        txtNCliente.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtNCliente.setText("Nombre:");
        getContentPane().add(txtNCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));

        txtNumero.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtNumero.setText("Numero: ");
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 20));

        txtCantidad.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtCantidad.setText("Cantidad:");
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, 20));

        txtFechaRetiro.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtFechaRetiro.setText("Fecha Retiro:");
        getContentPane().add(txtFechaRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, 20));

        txtPrecioAbonado.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtPrecioAbonado.setText("Precio Abonado:");
        getContentPane().add(txtPrecioAbonado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));

        txtCorreo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtCorreo.setText("Correo:");
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, 20));

        fSolicitud.setEditable(false);
        fSolicitud.setToolTipText("");
        fSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(fSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 130, -1));

        precioAbonado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioAbonadoActionPerformed(evt);
            }
        });
        getContentPane().add(precioAbonado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 130, -1));
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 450, -1));
        getContentPane().add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 150, -1));
        getContentPane().add(descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 70, -1));
        getContentPane().add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 130, -1));

        fRetiro.setText("dd/MM/aaaa");
        getContentPane().add(fRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 130, -1));

        boxProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxProductosActionPerformed(evt);
            }
        });
        getContentPane().add(boxProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 130, -1));
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 230, -1));

        boxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(boxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 130, -1));

        bVolver.setText("Volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });
        getContentPane().add(bVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, 50));

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(bGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 100, 50));

        precioTotal.setText("0");
        getContentPane().add(precioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, 20));

        btnAgregarProducto.setText("+");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 50, 30));

        txt$.setText("$");
        getContentPane().add(txt$, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, 20));

        txtPorcentaje.setText("%");
        getContentPane().add(txtPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 10, 20));

        btnAplicarDscto.setText("Aplicar");
        btnAplicarDscto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarDsctoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAplicarDscto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 80, 30));

        resumenPedido.setText("Resumen Pedido");
        getContentPane().add(resumenPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        listaProductos.setBackground(new java.awt.Color(242, 242, 242));
        listaProductos.setModel(new javax.swing.AbstractListModel<String>() {

            String[] strings = {"item 1"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }

        });
        listaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 190, 260));

        panelSuperior.setBackground(new java.awt.Color(153, 197, 175));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo64x64.png"))); // NOI18N

        titulo.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("NUEVO PEDIDO");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(icon)
                .addGap(18, 18, 18)
                .addComponent(titulo)
                .addContainerGap(477, Short.MAX_VALUE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(icon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(18, 18, 18))
        );

        getContentPane().add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondoLargo.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 780, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fSolicitudActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        cantidad.setText("");
        String pattern = "dd-MM-yyyy";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        Date hoy = new Date();
        fSolicitud.setText(simpleDateFormat.format(hoy));
        fRetiro.setText("dd/MM/aaaa");
        precioAbonado.setText("");
        precioTotal.setText("0");
        total = 0;
        contador = 0;
        descuento.setText("");
        nombre.setText("");
        numero.setText("");
        correo.setText("");
        productos = new HashMap<>();
        model.clear();
        ControladorInterfaces.mostrarNuevoPedido(false);
        ControladorInterfaces.mostrarGestionaPedido(true);
        
    }//GEN-LAST:event_bVolverActionPerformed

    private void boxProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxProductosActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        String nombreProducto = (String) boxProductos.getSelectedItem();
        Producto producto = null;
        for(Producto p: almacen.getProductos()){
            if (p.getNombre().equals(nombreProducto)){
                producto = p;
                break;
            }
        }
        
        try{
            int cant = Integer.parseInt(cantidad.getText());
            if(cant>0){
                if (productos.containsKey(producto)){
                    productos.replace(producto, cant);
                }
                else{
                    productos.put(producto,cant);
                }
                total += (producto.getPrecioVenta()*cant);
                precioTotal.setText(String.valueOf(total));
                this.model.clear();
                for(Producto p: productos.keySet()){
                    this.model.addElement("Producto: " + p.getNombre());
                    this.model.addElement("Cantidad: " + productos.get(p));
                    this.model.addElement("_______________________");
                }
                super.paintComponents(this.getGraphics());
            }
            else{
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor"
                        + "a cero.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero válido",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
        
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    /**
     * Falta verificar lo del cliente.
     * @param evt 
     */
    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        // TODO add your handling code here:
        boolean flag = false;
        boolean flag2 = false;
        boolean flag3 = true;
        boolean flag4 = true;
        boolean flag5 = true;
        boolean flag6 = true;
        boolean flag9 = true;
        Date DateSolicitud = null;
        Date DateRetiro = null;
        int abono = 0;
        int dcto = 0;
        
        try{
            abono = Integer.parseInt(precioAbonado.getText());
            dcto = Integer.parseInt(descuento.getText());
            flag = true;
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero válido",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            DateSolicitud =  new SimpleDateFormat("dd/MM/yyyy").parse(this.fSolicitud.getText());
            DateRetiro =  new SimpleDateFormat("dd/MM/yyyy").parse(this.fRetiro.getText());
            flag2 = true;
        } catch (ParseException ex) {
            Logger.getLogger(VistaNuevoPedido.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Debe ingresar una fecha válida",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (productos.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar al menos 1 producto",
                    "Error", JOptionPane.ERROR_MESSAGE);
            flag3=false;
        }
        
        if(abono>total){
            JOptionPane.showMessageDialog(this, "El abono no puede ser mayor al total",
                    "Error", JOptionPane.ERROR_MESSAGE);
            flag4 = false;
        }
        if(!(numero.getText().length() == 9 && numero.getText().charAt(0) == '9')){
            JOptionPane.showMessageDialog(this, "Ingrese un numero de telefono valido",
                    "Error", JOptionPane.ERROR_MESSAGE);
            flag5 = false;
        }
        if(!correo.getText().matches("^([0-9a-zA-Z]+[-._+&])*[0-9a-zA-Z]+@([-0-9a-zA-Z]+[.])+[a-zA-Z]{2,6}$")){
            JOptionPane.showMessageDialog(this, "Ingrese un correo valido",
                    "Error", JOptionPane.ERROR_MESSAGE);
            flag6 =false;
        }
        try {
            Date fSolicitud = new SimpleDateFormat("dd/MM/yyyy").parse(this.fSolicitud.getText());
            Date fRetiro =  new SimpleDateFormat("dd/MM/yyyy").parse(this.fRetiro.getText());
            Date fActual = new Date();
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");  
            String strDate = dateFormat.format(fActual);  
            fActual = new SimpleDateFormat("dd/MM/yyyy").parse(strDate);
            System.out.println(fActual);
            System.out.println(fSolicitud);
            System.out.println(fRetiro);
            
            if(fRetiro.before(fActual))
            {
                JOptionPane.showMessageDialog(this, "La fecha de retiro es anterior a la actual.",
                    "Error", JOptionPane.ERROR_MESSAGE);
                flag9 = false;
            }
        } catch (ParseException ex) {
            Logger.getLogger(VistaNuevoPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (flag && flag2 && flag3 && flag4 && flag5 && flag6 && flag9){
            Pedido p = new Pedido(productos, DateSolicitud, DateRetiro,
                    total,dcto,nombre.getText(), 
                    correo.getText(), numero.getText(), abono);
            ArrayList<Pedido> aux = almacen.getPedidos();
            aux.add(p);
            almacen.setPedidos(aux);
            JOptionPane.showMessageDialog(this, "Guardado exitosamente",
                        "Guardado", JOptionPane.INFORMATION_MESSAGE);
            cantidad.setText("");
            String pattern = "dd-MM-yyyy";
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
            Date hoy = new Date();
            fSolicitud.setText(simpleDateFormat.format(hoy));
            fRetiro.setText("dd/MM/aaaa");
            precioAbonado.setText("");
            total = 0;
            contador = 0;
            precioTotal.setText("0");
            descuento.setText("");
            nombre.setText("");
            numero.setText("");
            correo.setText("");
            
            productos = new HashMap<>();
            model.clear();
            ControladorInterfaces.mostrarNuevoPedido(false);
            ControladorInterfaces.mostrarGestionaPedido(true);

        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void precioAbonadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioAbonadoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_precioAbonadoActionPerformed

    private void btnAplicarDsctoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarDsctoActionPerformed
        // TODO add your handling code here:
        
        if(contador==0){
            double dcto = Double.parseDouble(descuento.getText());
            if(dcto<0 || dcto>100){
                JOptionPane.showMessageDialog(this, "El descuento debe estar entre 0 y 100",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                double precioDescontado = total*(1-(dcto/100));
                total = (int) precioDescontado;
                precioTotal.setText(String.valueOf(total));
                contador++;
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Solo se puede aplicar 1 vez el descuento",
                        "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAplicarDsctoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaNuevoPedido().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> boxCliente;
    private javax.swing.JComboBox<String> boxProductos;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnAplicarDscto;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField descuento;
    private javax.swing.JTextField fRetiro;
    private javax.swing.JTextField fSolicitud;
    private javax.swing.JLabel icon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numero;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTextField precioAbonado;
    private javax.swing.JLabel precioTotal;
    private javax.swing.JLabel resumenPedido;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txt$;
    private javax.swing.JLabel txtCantidad;
    private javax.swing.JLabel txtCliente;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtDescuento;
    private javax.swing.JLabel txtFechaRetiro;
    private javax.swing.JLabel txtFechaSolicitud;
    private javax.swing.JLabel txtNCliente;
    private javax.swing.JLabel txtNumero;
    private javax.swing.JLabel txtPorcentaje;
    private javax.swing.JLabel txtPrecioAbonado;
    private javax.swing.JLabel txtPrecioTotal;
    private javax.swing.JLabel txtProducto;
    // End of variables declaration//GEN-END:variables
}
